version: "3"

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "80:80"
  #   links:
  #     - freescout

  freescout:
    image: tiredofit/freescout
    ports:
      - 80:80
    links:
      - database
    volumes:
      - freescout_data:/data
    environment:
      CONTAINER_NAME: freescout
      CONTAINER_ENABLE_MONITORING: FALSE

      DB_HOST: database
      DB_NAME: freescout
      DB_USER: freescout
      DB_PASS: freescout

      SITE_URL: http://localhost
      ADMIN_EMAIL: admin@example.org
      ADMIN_PASS: password
      TIMEZONE: Europe/London

      ENABLE_SSL_PROXY: FALSE
      DISPLAY_ERRORS: TRUE
    restart: always

  database:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: freescout
      MARIADB_PASSWORD: freescout
      MARIADB_DATABASE: freescout

  uffd:
    build:
      context: ./uffd
    ports:
      - 5000:5000
    volumes:
      - uffd:/var/lib/uffd

volumes:
  freescout_data:
  database:
  uffd:
