version: "3"

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "80:80"
  #   links:
  #     - freescout

  freescout:
    image: tiredofit/freescout
    ports:
      - 80:80
    links:
      - database
      - uffd-ldap
    volumes:
      - freescout_data:/data
    environment:
      CONTAINER_NAME: freescout
      CONTAINER_ENABLE_MONITORING: FALSE

      DB_HOST: database
      DB_NAME: freescout
      DB_USER: freescout
      DB_PASS: freescout

      SITE_URL: http://localhost
      ADMIN_EMAIL: admin@example.org
      ADMIN_PASS: password
      TIMEZONE: Europe/London

      ENABLE_SSL_PROXY: FALSE
      DISPLAY_ERRORS: TRUE
    restart: always

  database:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: freescout
      MARIADB_PASSWORD: freescout
      MARIADB_DATABASE: freescout

  uffd:
    build:
      context: ./uffd
      target: web
    ports:
      - 5000:5000
    volumes:
      - uffd:/var/lib/uffd

  uffd-ldap:
    build:
      context: ./uffd
      target: ldap
    environment:
      SERVER_API_URL: http://uffd:5000
      SERVER_API_USER: ldap
      SERVER_API_SECRET: password
      SERVER_BASE_DN: dc=example,dc=org
      SERVER_BIND_PASSWORD: password
      SERVER_SOCKET_ADDRESS: 0.0.0.0:389
    ports:
      - 389:389
    links:
      - uffd

volumes:
  freescout_data:
  database:
  uffd:
