networks:
  default:
    enable_ipv6: true

services:
  freescout:
    build:
      context: ./freescout
    ports:
      - "127.0.0.1:8136:80"
    volumes:
      - freescout_data:/data
    depends_on:
      - database
    environment:
      CONTAINER_NAME: freescout
      CONTAINER_ENABLE_MONITORING: "FALSE"

      DB_HOST: database
      DB_NAME: freescout
      DB_USER: freescout
      DB_PASS: "${DATABASE_USER_PASSWORD}"

      SITE_URL: "${PROTOCOL}://${DOMAIN}${PORT:+:}${PORT:-}"
      ADMIN_EMAIL: "${FREESCOUT_ADMIN_EMAIL}"
      ADMIN_PASS: "${FREESCOUT_ADMIN_PASSWORD}"
      TIMEZONE: Europe/London

      ENABLE_SSL_PROXY: "FALSE"
      APP_NEW_FETCHING_LIBRARY: "TRUE"
      PHP_MEMORY_LIMIT: "256M"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    image: mariadb:12.2.2-noble
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MARIADB_USER: freescout
      MARIADB_PASSWORD: "${DATABASE_USER_PASSWORD}"
      MARIADB_DATABASE: freescout
    restart: always

volumes:
  freescout_data:
  database:
