version: "3"

services:
  freescout:
    build:
      context: ./freescout
    ports:
      - 8136:80
    volumes:
      - freescout_data:/data
    depends_on:
      - database
      - vouch
      - uffd-ldap
    environment:
      CONTAINER_NAME: freescout
      CONTAINER_ENABLE_MONITORING: "FALSE"

      DB_HOST: database
      DB_NAME: freescout
      DB_USER: freescout
      DB_PASS: "${DATABASE_USER_PASSWORD}"

      SITE_URL: "${PROTOCOL}://${DOMAIN}${PORT:+:}${PORT:-}"
      ADMIN_EMAIL: "${FREESCOUT_ADMIN_EMAIL}"
      ADMIN_PASS: "${FREESCOUT_ADMIN_PASSWORD}"
      TIMEZONE: Europe/London

      ENABLE_SSL_PROXY: "FALSE"
      DISPLAY_ERRORS: "TRUE"
      APP_NEW_FETCHING_LIBRARY: "TRUE"
    restart: always

  vouch:
    image: quay.io/vouch/vouch-proxy:0.39
    environment:
      VOUCH_DOCUMENT_ROOT: /vouch
      VOUCH_COOKIE_DOMAIN: "${DOMAIN}"
      VOUCH_COOKIE_SECURE: "${SECURE_COOKIES}"
      VOUCH_ALLOWALLUSERS: "true"
      VOUCH_POST_LOGOUT_REDIRECT_URIS: "${PROTOCOL}://${DOMAIN}${PORT:+:}${PORT:-}"
      OAUTH_PROVIDER: oidc
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      OAUTH_CALLBACK_URL: "${PROTOCOL}://${DOMAIN}${PORT:+:}${PORT:-}/vouch/auth"
      OAUTH_AUTH_URL: "${UFFD_EXT_URL:-${UFFD_URL}}/oauth2/authorize"
      OAUTH_TOKEN_URL: "${UFFD_URL}/oauth2/token"
      OAUTH_USER_INFO_URL: "${UFFD_URL}/oauth2/userinfo"

  database:
    image: mariadb:10.7
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MARIADB_USER: freescout
      MARIADB_PASSWORD: "${DATABASE_USER_PASSWORD}"
      MARIADB_DATABASE: freescout

  uffd-ldap:
    build:
      context: ./uffd
      target: ldap
    environment:
      SERVER_API_URL: "${UFFD_URL}"
      SERVER_API_USER: "${UFFD_LDAP_USER}"
      SERVER_API_SECRET: "${UFFD_LDAP_PASSWORD}"
      SERVER_BASE_DN: "${BASE_DN}"
      SERVER_BIND_PASSWORD: "${UFFD_LDAP_BIND_PASSWORD}"
      SERVER_SOCKET_ADDRESS: 0.0.0.0:389

volumes:
  freescout_data:
  database:
