version: "3"

services:
  uffd:
    build:
      context: ./uffd
      target: web
    ports:
      - 5000:5000
    volumes:
      - uffd:/var/lib/uffd
  
  freescout:
    environment:
      DISPLAY_ERRORS: "TRUE"

volumes:
  uffd:
