server {
  listen       *:80 default_server;
  listen       [::]:80 default_server;


  server_name  localhost;

  client_max_body_size 512M;
  index  index.html index.htm index.php;
  add_header "X-Content-Type-Options" "nosniff";
  add_header "X-Frame-Options" "SAMEORIGIN";

  location / {
    proxy_pass            http://freescout:80;
    proxy_read_timeout    90s;
    proxy_connect_timeout 90s;
    proxy_send_timeout    90s;
    proxy_http_version    1.1;
    proxy_set_header      Host "localhost:8137";
    proxy_set_header      Proxy "";
    proxy_set_header      X-Forwarded-Proto $scheme;
    proxy_set_header      Upgrade $http_upgrade;
    proxy_set_header      Connection $http_connection;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;

    auth_request /oauthproxy/auth;
    auth_request_set $auth_header $upstream_http_OAUTH_USER_NICKNAME;
    more_clear_input_headers REMOTE-USER;
    proxy_set_header REMOTE-USER $auth_header;
  }

  location /oauthproxy/ {
    proxy_pass            http://127.0.0.1:5002/;
    proxy_read_timeout    90s;
    proxy_connect_timeout 90s;
    proxy_send_timeout    90s;
    proxy_set_header      X-REDIRECT-URI "http://localhost:8137/oauthproxy/callback";
    proxy_set_header      X-CLIENT-ID "unsafe-static-client-id";
    proxy_set_header      X-CLIENT-SECRET "unsafe-static-client-secret";
    proxy_set_header      Content-Length "";
    proxy_pass_request_body off;
    proxy_redirect /cookiecheck /oauthproxy/cookiecheck;
  }

  error_page 401 = @error401;
  
  location @error401 {
    set_escape_uri $oauth_ret_url "http://localhost:8137$request_uri";
    return 302 "http://localhost:8137/oauthproxy/login?url=$oauth_ret_url";
  }
  
  more_clear_input_headers REMOTE-USER;
}

server {
  listen 127.0.0.1:5002;

  server_name           oauthproxy;

  location / {
    include /etc/uffd-nginxauth/nginx.include.conf;
  }
}
